-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 15:21:11 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projet_ecole
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema MonProjet_Ecole
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MonProjet_Ecole
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MonProjet_Ecole` DEFAULT CHARACTER SET utf8 ;
USE `MonProjet_Ecole` ;

-- -----------------------------------------------------
-- Table `MonProjet_Ecole`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MonProjet_Ecole`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MonProjet_Ecole`.`prestataire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MonProjet_Ecole`.`prestataire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `experience` ENUM('0-2ans', '2-5ans', '5-7ans') NOT NULL,
  `competence` VARCHAR(600) NULL,
  `titre` VARCHAR(100) NOT NULL,
  `tarif` VARCHAR(50) NULL,
  `telephone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MonProjet_Ecole`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MonProjet_Ecole`.`message` (
  `destinateur` VARCHAR(45) NOT NULL,
  `texte` LONGTEXT NULL,
  `users_idusers` INT NOT NULL,
  `prestataire_id` INT NOT NULL,
  PRIMARY KEY (`users_idusers`, `prestataire_id`),
  CONSTRAINT `fk_message_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `MonProjet_Ecole`.`users` (`idusers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_message_prestataire1`
    FOREIGN KEY (`prestataire_id`)
    REFERENCES `MonProjet_Ecole`.`prestataire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_message_users1_idx` ON `MonProjet_Ecole`.`message` (`users_idusers` ASC);

CREATE INDEX `fk_message_prestataire1_idx` ON `MonProjet_Ecole`.`message` (`prestataire_id` ASC);


-- -----------------------------------------------------
-- Table `MonProjet_Ecole`.`mission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MonProjet_Ecole`.`mission` (
  `titre` VARCHAR(45) NOT NULL,
  `description` VARCHAR(400) NULL,
  `date` DATE NOT NULL,
  `type_prestattion` ENUM('mariage', 'anniversaire', 'seminaire', 'autre') NOT NULL,
  `users_idusers` INT NOT NULL,
  `prestataire_id` INT NOT NULL,
  PRIMARY KEY (`users_idusers`, `prestataire_id`),
  CONSTRAINT `fk_mission_users1`
    FOREIGN KEY (`users_idusers` , `prestataire_id`)
    REFERENCES `MonProjet_Ecole`.`users` (`idusers` , `idusers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_mission_prestataire1`
    FOREIGN KEY (`prestataire_id`)
    REFERENCES `MonProjet_Ecole`.`prestataire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_mission_prestataire1_idx` ON `MonProjet_Ecole`.`mission` (`prestataire_id` ASC);


-- -----------------------------------------------------
-- Table `MonProjet_Ecole`.`portfolio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MonProjet_Ecole`.`portfolio` (
  `nom` VARCHAR(225) NULL,
  `img_dir` VARCHAR(225) NULL,
  `prestataire_id` INT NOT NULL,
  PRIMARY KEY (`prestataire_id`),
  CONSTRAINT `fk_portfolio_prestataire1`
    FOREIGN KEY (`prestataire_id`)
    REFERENCES `MonProjet_Ecole`.`prestataire` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MonProjet_Ecole`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MonProjet_Ecole`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `validad` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
